// front/src/components/message_form.tsx
import client, { Message } from "~/lib/message_client"
import { useCallback, useRef, FormEvent } from "react"

export default function MessageForm() {
  const ref = useRef<HTMLInputElement>(null)
  const post = useCallback((event: FormEvent) => {
    event.preventDefault()

    const body = ref.current?.value
    if (body == null || body === "") {
      throw new Error("body is empty")
    }

    client.post(new Message({ body }))
    ref.current.value = ""
  }, [])
  return (
    <form onSubmit={post}>
      <input ref={ref} type="text" />
      <input type="submit" disabled={ref.current && ref.current?.value === ""} value="Post" />
    </form>
  );
}

// front/src/components/message_form.svelte
<script lang="ts">
	import client, { Message } from "~/lib/message_client"

	let body = ""

	function submit() {
    event.preventDefault()
    client.post(new Message({ body }))
		body = ""
	}

	$: submitDisabled = body === ""
</script>

<form on:submit={submit}>
	<input type="text" bind:value={body} />
	<input type="submit" disabled={submitDisabled} value="Post" />
</form>
