// front/src/components/top.svelte
<script lang="ts">
	import { onMount } from "svelte"
	import MessageList from "~/components/message_list.svelte"
	import MessageForm from "~/components/message_form.svelte"
	import SignUpForm from "~/components/signup_form.svelte"
	import client from "~/clients/authentication_client"
	import session, { authentication } from "~/stores/session"

	onMount(() => {
		authentication(client.isSignedIn())
	})

	$: isSignedIn = $session === "authenticated"
</script>

{#if $session === "authenticated"}
	<MessageForm />
	<MessageList />
{:else if $session === "unauthenticated"}
	<SignUpForm />
{:else}
	<div class="text-white">loading...</div>
{/if}

// front/src/components/top.tsx
import { useEffect } from "react"
import MessageList from "~/components/message_list"
import MessageForm from "~/components/message_form"
import SignUpForm from "~/components/signup_form"
import { useSessionState, authentication } from "~/lib/session_state"
import client from "~/lib/authentication_client"

export default function Top() {
  const status = useSessionState()
  useEffect(() => authentication(client.isSignedIn()), [])
  return (<>
    { status === "loading" ? <div></div> : status === "unauthenticated" ? <SignUpForm /> : <MessageForm /> }
    <MessageList />
  </>);
}
